config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "projects#index"
  resources :projects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
    validates_presence_of :title, :description
  end
  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]

  before_action :authenticate_user!, except: [:show, :index]

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to project_url(@project), notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to project_url(@project), notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cs3300</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <%= link_to root_path, class: "nav-link #{'active font-weight-bold' if current_page?(root_path)}" do %>
            <div class="fa fa-home"></div>
            Home
          <% end %>
        </ul>
        <ul class="navbar-nav mr-right">
          <% if current_user %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <div class="fa fa-user"></div>
                <b><%= current_user.email %></b>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to edit_user_registration_path, class: "dropdown-item #{'active font-weight-bold' if current_page?(edit_user_registration_path)}" do %>
                  <div class="fa fa-cog"></div>
                  <b>Account settings</b>
                <% end %>
                <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
                  <div class="fa fa-sign-out-alt"></div>
                  <b>Sign out</b>
                <% end %>
              </div>
            </li>
          <% else %>
            <%= link_to "Log in", new_user_session_path, class: "nav-link #{'active font-weight-bold' if current_page?(new_user_session_path)}" %>
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link #{'active font-weight-bold' if current_page?(new_user_registration_path)}" %>
          <% end %>
        </ul>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <h3 align="center"><%= form.label :title %></h3>
    <p align="center"><%= form.text_field :title %></p>
    
  </div>

  <div class="field">
    <h3 align="center"><%= form.label :description %></h3>
    <p align="center"><%= form.text_area :description %></p>
    
  </div>


  <div class="actions">
    <p align="center"><%= form.submit %></p>
    
  </div>

<% end %>

app/views/projects/edit.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <p class="lead"><%= render 'form', project: @project %></p>
    <p align="center">
        <a class="btn btn-primary btn-sm" <%= link_to 'Show', @project %></a>
        <a class="btn btn-primary btn-sm" <%= link_to 'Back', projects_path %></a>
    </p>
  </div>
</div>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../../../favicon.ico">

  <title>Jumbotron Template for Bootstrap</title>

  <!-- Bootstrap core CSS -->
  <link href="../../../../dist/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="jumbotron.css" rel="stylesheet">
</head>

<body>

  <main role="main">

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1 class="display-3">Logan Weberg</h1>
        <p>This is my portfolio.</p>
        <p><a class="btn btn-primary btn-lg" <%= link_to "New Project", new_project_path %></a></p>
      </div>
    </div>

    
    <h1 align="center">Projects</h1>

<tbody>
  <% @projects.each do |project| %>
    <tr>
    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2><%= project.title %></h2>
          <p>
            <span class="d-inline-block text-truncate" style="max-width: 300px;">
              <%= project.description %>
            </span>
          </p>
          
          <p>
            <a class="btn btn-link btn-sm" <%= link_to 'Show', project %></a>
            <a class="btn btn-link btn-sm" <%= link_to 'Edit', edit_project_path(project) %></a>
            <a class="btn btn-danger btn-sm" <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></a>
          </p>
        </div>
      </div>

      <hr>

    </div> <!-- /container -->

      
    </tr>
  <% end %>
</tbody>

app/views/projects/new.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <p class="lead"><%= render 'form', project: @project %></p>
    <p align="center">
        <a class="btn btn-primary btn-sm" <%= link_to 'Back', projects_path %></a>
    </p>
  </div>
</div>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
  <h1 class="display-4"><%= @project.title %></h1>
  <hr class="my-4">
  <p><%= @project.description %></p>
  <p class="lead">
    <a class="btn btn-primary btn-sm" <%= link_to 'Edit', edit_project_path(@project) %></a>
    <a class="btn btn-primary btn-sm" <%= link_to 'Back', projects_path %></a>
  </p>
</div>